version: "3.8"

services:
  app:
    build:
      context: .
    ports:
      - "8000:8000"
    environment:
      DATABASE_URL: postgresql://postgres:123@db:5432/sprkl-test?schema=public
    depends_on:
      - db

  db:
    image: postgres
    environment:
      POSTGRES_DB: sprkl-test
      POSTGRES_PASSWORD: 123
    volumes:
      - db-data:/var/lib/postgresql/data

  migrate:
    build:
      context: .
    command: ["npx", "prisma", "migrate", "deploy"]
    environment:
      DATABASE_URL: postgresql://postgres:123@db:5432/sprkl-test?schema=public
    depends_on:
      - db

volumes:
  db-data:
